# Generated by Django 3.1 on 2021-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='main_currency',
        ),
        migrations.AddField(
            model_name='userss',
            name='main_currency',
            field=models.CharField(blank=True, choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('USD', 'US Dollar'), ('JPY', 'Janpanese Yen')], max_length=3, null=True),
        ),
    ]
