# Generated by Django 3.1 on 2021-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20210113_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
